# Generated by Django 5.0.6 on 2024-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_advert_rating_alter_category_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена'),
        ),
    ]
