# Generated by Django 5.0.6 on 2024-07-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_advert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='board/', verbose_name='Изображения'),
        ),
    ]
